name: Run auto_tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select test to run
        required: true
        type: choice
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Copy source code
        uses: actions/checkout@v4
      - name: Set up Python eny
        uses: actions/setup-python@v5
        with:
          pytho-version: "3.13.0"
      - name: install dependencies
        run: pip install requirements.txt
      - name: Run tests
        run: pytest -v


